### ISSUE TITLE
[BUG] i18n 默认解析时，同时支持 `yml` 与 `yaml`

### ISSUE THREAD

**Issue by shuqingzai** [go-cinch/common#1]
现在无法支持 `yaml` 格式，仅支持 `yml` ，但是 `yml` 与 `yaml` 应该是一样的

是否可以在注册 `yml` 的同时也注册 `yaml` 格式？？

https://github.com/go-cinch/common/blob/27527952d4b77d35afe1b4a525ac075ac851605a/i18n/i18n.go#L36

**Comment by piupuer** [comment]
谢谢你指出bug, 已修复, 请查看`i18n/v1.0.4`
